### ISSUE TITLE
executable is not written into top-level spiral directory 

### ISSUE THREAD

**Issue by petermcLBL** [spiral-software/spiral-software#58]
When I build Spiral on cori.nersc.gov, the spiral executable is placed into bin/spiral, and not into the top-level spiral directory as it is supposed to be.

It did not work to do "ln -s bin/spiral spiral" or "cp bin/spiral spiral", because then gap could not be found. The workaround that worked for me was to add a new file called spiral in the top-level spiral directory containing one line with the full file path to bin/spiral.

**Comment by broderickpt** [comment]
This change is in preparation for being able to build & release spack packages.   The spack package will create a module that can be loaded in order to use spiral; that module assumes a top-level bin directory,  that will get added to a user's path (along with the appropriate setting for SPIRAL_HOME).  Apologies if this causes temporary inconvenience but it is a necessary change.
